### PR TITLE
First working version of cmd/flying

### PR DESCRIPTION
**Pull request by rjeczalik**
- [x] cmd/flying: Add simple running and logging of child process
- [x] cmd/flying: Format child processes output
- [x] cmd/flying: Forward interruption signals to child process 
- [ ] cmd/flying: Support running as a Windows service

### CODE REVIEW

**Comment by rjeczalik** [comment]
> https://ci.appveyor.com/project/rjeczalik/flyingexec-142/build/21

Something environmental, I tried to reproduce the failure under:
- go1.3/amd64 on Windows Server 2012 R2 (this is what AppVeyor uses)
- go1.3.3amd64 on Windows Server 2012 R2
- go1.3.1/386 on Windows 8.1 (without `-race`)
- go1.3.1/amd64 on Windows 8.1

without success.

**Comment by ppknap** [comment]
- go1.3.3/amd64 on Windows 8.1
  and still no races..

**Comment by rjeczalik** [comment]
@ppknap Thx for checking, but probably I've found the weak point [here](https://github.com/rjeczalik/flyingexec/commit/60b7c3fded3b9ca0b38d2b133b5992f5b5afc657#diff-ce45de33536d78cf48ddf4b5d85f226eR33). I'm going to rework this `WatchedWriter` anyway.

**Comment by rjeczalik** [comment]
@ppknap Could you check sth for me? Wondering if:

``` bash
~ > cmd /c go test -race -v ./...
```

can kill the shell session? And the same with PowerShell. Wanted to fix [this](https://ci.appveyor.com/project/rjeczalik/flyingexec-142/build/26).

**Comment by ppknap** [comment]
```
C:\projects\src\github.com\x-formation\flyingexec>cmd /c go test -race -v ./...
?       github.com/x-formation/flyingexec/cmd/flying    [no test files]
?       github.com/x-formation/flyingexec/cmd/flyingd   [no test files]
=== RUN TestHelperProcess
--- PASS: TestHelperProcess (0.00 seconds)
=== RUN TestClientInterrupt
[2014-10-09 20:09:36] flying: started with command=C:\Users\Pawel\AppData\Local\Temp\go-build989971059\github.com\x-formation\flyingexec\flying\_test\flying.test.exe, args=[-test.run=TestHelperProcess, --, TestClientInterrupt], CWD=C:\projects\src\github.com\x-formation\flyingexec\flying
[2014-10-09 20:09:36] [C:\Users\Pawel\AppData\Local\Temp\go-build989971059\github.com\x-formation\flyingexec\flying\_test\flying.test.exe] TestClientInterrupt ready
flying ready
[2014-10-09 20:09:36] [C:\Users\Pawel\AppData\Local\Temp\go-build989971059\github.com\x-formation\flyingexec\flying\_test\flying.test.exe] child interrupted
[2014-10-09 20:09:36] flying: exited successfully
--- PASS: TestClientInterrupt (0.14 seconds)
PASS
ok      github.com/x-formation/flyingexec/flying        1.384s
```

**Comment by ppknap** [comment]
Powershell died when I ran your test...

**Comment by ppknap** [comment]
image
It seems that powershell caught one of your test signals:<

**Comment by ppknap** [comment]
```
build_script:
 - go tool vet -all .
 - go build ./...
 - cmd /c go test -race -v ./...
```

This should help you :smile: :

```
build_script:
 - go tool vet -all .
 - go build ./...
 - cmd
 - go test -race -v ./...
```

[edit] 
but it kills PS :-1:

**Comment by rjeczalik** [comment]
> This should help you :smile: :
> 
> ```
> build_script:
>  - go tool vet -all .
>  - go build ./...
>  - cmd
>  - go test -race -v ./...
> ```

Oh, you [got me](https://ci.appveyor.com/project/rjeczalik/flyingexec-142/build/28).

trolled

**Comment by ppknap** [comment]
image

;P

**Comment by ppknap** [comment]
https://connect.microsoft.com/feedback/ViewFeedback.aspx?FeedbackID=180072&SiteID=99

`Posted by Microsoft on 9/5/2006 at 3:32 PM
This is By Design. This feature was specified to be this way. Thanks`

**Pull request merged**
